FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /app
COPY gradlew build.gradle settgins.gradle /apap/
COPY gradle /app/gradle

COPY src /app/src

RUN chmod +x ./gradlew && .grdlew clean build -x test

FROM eclipse-temuriin:21-jre-alpine
WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/app/app.jar"]